### ISSUE TITLE
Major Limitations

### ISSUE THREAD

**Issue by GrahamCampbell** [parse-community/parse-php-sdk#18]
We can only have one instance of the client because it's all static. This is a major blocker for me.

**Comment by svycka** [comment]
@GrahamCampbell how you solved this? authors of this lib have some serious problems with static methods :D maybe you know alternative for this sdk? it is really hard to use this without ability to create two clients and makes mission impossible for testing.
@gfosco maybe you have any plans removing this static thing?
before every call for the api I have to do:
```php
ParseClient::initialize( $app_id, $rest_key, $master_key );
// call api
```
as I don't know with app is initialized really annoying. Also I cant add this as dependency through constructor so it is VERY hard to test.

This is first time I see library written this way and don't know how to workaround these limitations.

**Comment by GrahamCampbell** [comment]
> how you solved this?

I didn't.

**Comment by svycka** [comment]
@GrahamCampbell why did you close this? maybe they will consider and remove this in new version but now it is closed and forgotten.

**Comment by GrahamCampbell** [comment]
Because it's a nofix.

**Comment by gfosco** [comment]
Right now, we don't have the time/resources available to change the whole SDK from static to instance... Maybe the future will change things, as I do think there is interest in doing this across all the SDKs.

**Comment by Rican7** [comment]
Welp... http://blog.parse.com/announcements/moving-on/

**Comment by svycka** [comment]
looks like this solves the issue :D
