### ISSUE TITLE
Missing/inconsistent ParseException codes

### ISSUE THREAD

**Issue by izimodo** [parse-community/parse-php-sdk#180]
Looking at the code, it seems like SDK is using the code property of ParseException to represent many different things:
1. libcurl's internal error codes
2. HTTP status codes
3. Parse REST API error codes
I understand that these sets of values do not overlap (curl uses code values 0-99). But most of the time, SDK does not assign the exception code at all. This inconsistency makes writing exception handling code very hard, as your only option is to parse the exception message string in order to determine what exactly went wrong.
This can be most notably seen in ParseUser class:

``` php
if (!$username) {
    throw new ParseException('Cannot log in user with an empty name');
}
```

According to [http://docs.parseplatform.org/php/guide/#error-codes](http://docs.parseplatform.org/php/guide/#error-codes) the above code should set exception code to 200:

``` php
if (!$username) {
    throw new ParseException('Cannot log in user with an empty name', 200);
}
```

**Comment by gfosco** [comment]
Good points... Are you interested in submitting a pull request to address some of these?

**Comment by montymxb** [comment]
Closing with #334 having been merged in specifically to address this.
