### ISSUE TITLE
Adding a Class to my Database through Parse.com Dashboard causes "Empty Server Response" in future PHP queries ...

### ISSUE THREAD

**Issue by Lwdthe1** [parse-community/parse-php-sdk#232]
When I went to sleep, my php & JS app was working fine connected to my self hosted parse server hosted on mongoLab. When I woke up and added a new class to my database through the Parse dashboard, trying to query my database through php is halting and returning Empty Server response. After I deleted the new class through the dashboard and waiting 10 minutes for changes to propagate, my requests were back to normal and working again.... Why can't I add a new class to my database as I did without an error occurring?

**Comment by montymxb** [comment]
This could have been an issue regarding the service hosted on mongo lab. A server's response is inherently out of control of the sdk. If the server was temporarily having issues and giving bad responses that would have caused your issues. Rather vague but it's probable.

With that being said, this is a bit old and I'm not sure if you are still having issues with this or have managed resolve it? If you haven't had any progress and suspect an issue with the sdk it would be helpful if you could add any relevant information that we could use to try and pinpoint your issue.

As a side note I would be interested if perhaps there was a discrepancy in the layout for the new class. That could potentially lead to an issue causing the php sdk to crash out. Again, these are just conjectures, we'd need to know more to make any recommendations.
