### ISSUE TITLE
ParseFile Object with external url

### ISSUE THREAD

**Issue by kiettran** [parse-community/parse-php-sdk#239]
Hi there,

Is there a away to create an ParseFile object with an external file url that is actually located on your own file host services instead of Parse File Hosts?

For what I have read on the documentation, you can only create from data oar a file but that file will be uploaded to Parse Files.

I hope that there is such kind of an option or way to work around.

**Comment by montymxb** [comment]
I don't believe there is a way to do this using ```ParseFile```. However you can solve this by creating a new class that stores references to your external files, like so.

```php
// create an external file
$externalFile = new ParseObject("ExternalFile");
$externalFile->set("url", "http://example.com/your/file/location");
$externalFile->save();
```

You will probably want to add more data than this and do additional checking but it's just about that. To get your file you can run something simple like
```php
$contents = file_get_contents($externalFile->get("url"))
```
or you can work with curl if you want additional control.

**Comment by montymxb** [comment]
Closing this as it's been some time. There are several file adapter options in parse-server, using mongodb, Amazon S3 and Google Cloud Storage, you can read more about that [here](https://github.com/parse-community/parse-server/#configuring-file-adapters).
