### ISSUE TITLE
Can't get roles from logged user

### ISSUE THREAD

**Issue by paligiannis** [parse-community/parse-php-sdk#259]
I am breaking my head to find a way to get the Roles assigned to a user.
When I am trying to access the property of the currentUser object the error is that the permissions are in private variables.

**Should I try to query the _Role collection or the user itself to determine if the user has for ex. the Moderate role?**

(I want to create a authorization feature examining the user privileges and redirect him to an other page)

**Comment by montymxb** [comment]
A bit old but here's some code that I've used that seems to do the trick.
```php
// get the current user
$user = ParseUser::getCurrentUser();

// query for roles that this user is a part of
$query = new ParseQuery("_Role");
$query->containedIn("users", [$user]);
$roles = $query->find(true);
```

From there you can pull the name by calling ```$role->getName()``` or ```$role->get("name")``` and run any checks you need to from there.

**Comment by montymxb** [comment]
Closing as 'solved' in the last post.
