### ISSUE TITLE
Getting Bad Request error (Heroku)

### ISSUE THREAD

**Issue by thmohd** [parse-community/parse-php-sdk#272]
I was able to install parse server on Heroku and I installed the dashboard and the connection works fine, I was able to make query using CURL but when I try to do anything with Parse Client in php it always give me BAD REQUEST and can't connect to the server.

Any suggestion?

**Comment by maplethorpej** [comment]
Having the same issue. I'll post a resolution if I can figure it out.

**Comment by maplethorpej** [comment]
@thmohd check out this issue: https://github.com/ParsePlatform/parse-php-sdk/issues/252

**Comment by montymxb** [comment]
Curious did either of you find a resolution to this?

**Comment by thmohd** [comment]
I couldn't solve that. However, I moved to AWS and it worked fine with the same settings. It looks like there is some restriction to access the server on Heroku .

**Comment by montymxb** [comment]
Interesting, we'll keep this open in case someone else runs into this.

**Comment by soniurvashi11** [comment]
@thmohd I faced the same issue..found out..while pointing to self hosted parse server from php sdk, I was placing one extra "/" (slash) after the URL .Double check your server URL while putting it into ur app for initialization.

**Comment by montymxb** [comment]
@soniurvashi11 I think that's no longer an issue in the sdk. There's an ```rtrim``` call to remove any extra forward slashes after the ```serverUrl``` parameter in ```ParseClient::setServerURL```. Same goes for the ```mountPath```, except that's a flat out ```trim``` for slashes on both sides. It may have been an issue in an older version of the sdk though.

**Comment by montymxb** [comment]
Closing as this is fairly out of date now. If it comes up again we'll readdress it.
