### ISSUE TITLE
Uncaught Error: Class 'Parse\ParsePushStatus' not found in /app/vendor/parse/php-sdk/src/Parse/ParseClient.php:142

### ISSUE THREAD

**Issue by titadone** [parse-community/parse-php-sdk#298]
I have this error since i update the new version of parse php

Uncaught Error: Class 'Parse\ParsePushStatus' not found in /app/vendor/parse/php-sdk/src/Parse/ParseClient.php:142

**Comment by montymxb** [comment]
@titadone `ParsePushStatus` is automatically registered in `ParseClient::initialize`. If you are requiring the `autoload.php` when you clone this repository, or `./vendor/autoload.php` when you use composer should automatically load in the appropriate class there. Can you elaborate on how you are loading up your project? Perhaps if you could put up a code snippet of where you are setting this up and experiencing the error we can help you a bit more.

Be sure to remove any identifying keys or secrets from your code before posting too.

**Comment by montymxb** [comment]
If this is still an issue feel feel to let us know and we'll reopen this. This is rather old now, and probably an error on your end with integrating the project.
