### ISSUE TITLE
create new tag

### ISSUE THREAD

**Issue by acinader** [parse-community/parse-php-sdk#302]
@montymxb i'd like a new tag to reference in composer.  Is it ok to just create a new tag for 1.2.6?

I think its ok for this to be a patch level release, but since it is at least potentially breaking (though in practice i think it can only be "un-breaking", we could do a minor release to 1.3.0.  I think it should just be 1.2.6, but pointing out.....

**Comment by montymxb** [comment]
@acinader  Oops meant to put a tag in there after that last PR. Considering it's just a patch I think [1.2.6](https://github.com/parse-community/parse-php-sdk/releases/tag/1.2.6) is spot on, which is up now. I would imagine this would fix issues more than causing anything undesirable, tests looked ok but you never know...

Thanks for bringing this up again!
