### ISSUE TITLE
Relation query not working as hoped

### ISSUE THREAD

**Issue by khawtf** [parse-community/parse-php-sdk#304]
I cant wrap my head around this Many2Many relations in Parse.
This should be really simple but I cant get it to work.

I have two Collections (i will only write the columns with relation data to keep it easy to read)

**Location** 

- - deals (many to many relation to **Deal**)

**Deals**

- - locations (many to many relation **Location**)

I just want to get the locations near me with the deals without too much requests. 
So i thought i will combine them in one query like this:

```
//Location query
$locQuery = new ParseQuery("Location");
$locQuery->withinKilometers("geopoint", $geopoint, $maxdistance);

//Deal query
$dealsQuery = new ParseQuery("Deal");
$dealsQuery->matchesQuery("locations", $locQuery);

//Get from DB
$result = $dealsQuery->find();
```

But now I only have the deals but not the deals with location. 
_So I have no clue which deal belongs to which location!_

I cannot use Include because you can only use that with pointers but I have a relation. 

How can I make this easy stuff working ?

**Comment by montymxb** [comment]
@khawtf sounds like you have a bit of a conundrum, I wouldn't jump to calling this easy stuff right off the bat. The way you've set this up you won't be able to get the locations on the deals specifically without performing an additional query for each deal's locations. You _could_ query for all the locations using `$locQuery`, but that wouldn't help you differentiate between which locations are tied to which deals.

If you want to definitely return deals which are tied to locations you could try something else. Taking the result of `$locQuery` and for each `Location` returned run a query for deals containing that location. Assuming you have more deals than locations, it would be more efficient to go about it this way, and you would know that the deals you are returning per query have _at least_ that location on them.

If you wanted to provide _all_ the locations on a deal you would still have to make an extra relational query on `locations` to get that.

Parse makes it easy to perform the operations of saving, updating, etc., but it's still up to you to make sure you design your DB structure appropriately. If you find that you're having an issue with latency due to queries perhaps you should be consider redesigning your DB to facilitate querying in the appropriate circumstances. Maybe you'll find that having a location pointer on each deal is easier, even if you have to create multiple deals to cover multiple locations. It's up to you to decide this of course. 

Also this kind of question is more appropriate for [stackoverflow.com](https://stackoverflow.com/). However with that being said we're always happy to help out here too.

**Comment by khawtf** [comment]
@montymxb thanks! I really thought it was something that the php library was lacking. 

If I go either route you suggested it is probably not scalable. If you have 50 stores you need to do a request 50 times. That's way too much. 

So in essence my DB design is bad. I thought I thought it through this time :| 

This is where a many to many relation is for or not ? 

If created a custom collection like Location_Deals
With pointers to both classes. And query the Location table first and get the locations. After that use the custom collection with include on deal where location IN locations. 

Is that the best way. I really can't think anything else. How would you do it if you had total freedom ? Each location can have many deals and each deal can have many locations. 

Or is duplication the only way. Because then it's more a 1 to many or not ? Not inner joining is so hard

**Comment by montymxb** [comment]
Well I wouldn't go so far to say it's bad _overall_, it's just difficult to work with in Parse. In another setup this would appropriate though.

 Internally there are actually Join tables which are used for relations, but these are not not intended to be exposed externally. As far as I'm aware you'll only be able to get back one class's worth of objects per query with the current setup. This inherently limits you from achieving what you want.

_However_, if you want to keep the current design but know exactly which deals have which locations you could try adding a new array field like `locationIds` or `dealIds`. The idea here would be that when you want to add an object to a relation you would also add it's id to the array on the same object. This way you can know which IDs are associated with which objects, without having to make the second query. It's a bit redundant but it would allow you to make this work.

In the example above you could actually run both queries, `$locQuery` and `$dealsQuery` to get back _all_ the applicable deals and locations. Assuming you have an array field like `locationIds` on each Deal object, you can sift through the locations that were returned to match which locations are on which deals. It would just require you to modify your code to add/remove entries from the appropriate array in addition to the relation itself (wouldn't want to have incorrect array entries hanging out). You would also need to update all existing entries so this array was present and up to date.

It's not exactly the best design, but given the circumstances this is at least one way you can achieve many to many _without_ the extra queries. Many to many works, it's just usually you're going to have to deal with the extra overhead of the additional queries.

**Comment by flovilmart** [comment]
parse don't support multiple geo indexes (mongoDB either), so it's not possible at the moment to store arrays of GeoPoints. 

Now, I believe the design isn't as bad as you would think, you can use matchesQuery and/or matchesKeyInQuery. So you'd build a 'LocationQuery' that would return filter the closest location, and then match the 'location' relation on that from the Deals query. This should work.

**Comment by flovilmart** [comment]
Have a look there: https://github.com/parse-community/parse-server/blob/master/spec/ParseRelation.spec.js#L584

This test is covering a similar use case.

An Owner has Restaurants (relation to Restaurant)
A Restaurant has a rating, and a town
A Person, has a hometown.

The test builds a single query that will find the people that have the same hometown as a restaurant belonging to a single owner with a rating > 4.

More information on the $select operator: http://docs.parseplatform.org/rest/guide/#query-constraints

**Comment by montymxb** [comment]
@khawtf well looks like you have some samples now! Hopefully you'll be able to come up with something to address your specific problem. Let us know if you have any other questions.

**Comment by khawtf** [comment]
its still in development. I had to change my db design when I found that I cant do the things I wanted to do. So I am still All-In for changing the database design to do it right. But somehow i can't find the good working solution.

@montymxb using an array is in this scenario not scaleable because a location can have allot of deals over time and it also requires allot of write. (deals are added daily) 

@flovilmart  I am doing that at the moment matching the query so in 1 query you will indeed get the deals with the correct locations. but now you dont know which location is with which deal... btw Location is not a geopoint. You can see it as a Shop collection :)

The only good examples I can find on the web are SQL db's who use inner joins on tables to do it in 1 query. But with NOSQL db's this seems something not common...

The only thing I can think of is creating a join_table...does that sound good?

**Comment by flovilmart** [comment]
Creating your own join table is a great idea, that will solve your issue and it's a common design to avoid cluttering your base objects, then you just have to query this table with including both shops and deals

**Comment by montymxb** [comment]
@khawtf a join table sounds like a good approach. You could put something together like so...

- Join_Location_Deals
    - location [pointer]
    - deal [pointer]

In this sense a query could be made like so to fetch all locations and deals in one go.
```php
$joinQuery = new ParseQuery('Join_Location_Deals');

// match to your object
$joinQuery->equalTo('location', $locationToMatch);

// include both objects
$joinQuery->includeKey(['location','deal']);

$joinTableObjects = $joinQuery->find();

// assuming there's at least one...
$location = $joinTableObjects[0]->get('location');
$deal = $joinTableObjects[0]->get('deal');
```
For handling multiple locations you could do something like...
```php
// query for locations (what you had originally for your query approach)
$locQuery = new ParseQuery("Location");
$locQuery->withinKilometers("geopoint", $geopoint, $maxdistance);

// match to locations from $locQuery
$joinQuery->matchesQuery('location', $locQuery);

// include both objects
$joinQuery->includeKey(['location','deal']);

$joinTableObjects = $joinQuery->find();
// etc.
```
Granted that doesn't tell you how to manage the join table, keeping references up to date and such. But that would allow you to do one big query for all the data, while knowing which deals have which locations.

**Comment by khawtf** [comment]
Thanks for your great help guys 👍 I can continue my work with the new insights!
The issue is solved. 

It was more a design flaw than the SDK itself!
