### ISSUE TITLE
please correct the php Relation implementation doc at http://docs.parseplatform.org/php/guide/#relations

### ISSUE THREAD

**Issue by akshaychauhan7737** [parse-community/parse-php-sdk#321]
hello,
  please correct parse php guide for Relation at : http://docs.parseplatform.org/php/guide/#relations
the code there is the js code not the php code..
I could not find a contact form on http://docs.parseplatform.org/ so i am adding this as a issue over here

**Comment by montymxb** [comment]
@akshaychauhan7737 I took a look at the docs, it seems that's not the only section that seems to be JS code instead. Parts of the **Security** section are incorrect as well. Thanks for bringing this to our attention, we'll look into where the old references have gone and we'll get those back if we can.

**Comment by montymxb** [comment]
This issue has been moved over to the relevant doc mentioned above. You can keep an eye out there for any progress that's made.

**Comment by montymxb** [comment]
@akshaychauhan7737 just notifying you that I was able to find the underlying issue and have since pushed up a PR to docs. Once that's approved this will correct the observed issue not just in the php sdk but in all others as well.

**Comment by montymxb** [comment]
A [patch](https://github.com/parse-community/docs/pull/443) has been merged in for this issue. Docs look good now 👍 . Thanks for bringing this to our attention!
