### ISSUE TITLE
Github Continous Integration

### ISSUE THREAD

**Issue by montymxb** [parse-community/parse-php-sdk#323]
I was thinking about adding in Travis CI (or the like) for integration testing on PRs, instead of having to double check the tests ourselves.

Upon looking into this it looks like this repository, at one point, had codecov setup for running integration tests. It appears to be that the configuration has since lapsed and is no longer functional from what I can tell. I am following up at the moment with github support on that.

@flovilmart besides codecov it would be ideal to have Travis CI here. Is there a centralized account we should set this up under on behalf of **parse-community**, or is it fine if I set it up?

**Comment by flovilmart** [comment]
The parse-community is already enabled for CI with travis, I believe I can add the repo and you should be good to go!

**Comment by flovilmart** [comment]
I Just added travis, when you have a minute, just follow the php setup and we'll be good to go! Or I can give it a try: https://docs.travis-ci.com/user/languages/php/

**Comment by montymxb** [comment]
Gotcha, okay so we're already good on that end then. As for running the tests I'll have to configure a way to start parse-server instance for testing against. I'll have to take a look at the existing implementations to see if there's already a decent approach for this.
