### ISSUE TITLE
Cannot retrieve getCreatedAt()

### ISSUE THREAD

**Issue by ojoaldato** [parse-community/parse-php-sdk#33]
Hi!

I am retrieving my object properly and accessing all the fields except from the dates.

I tried calling $obj->getCreatedAt() but it returned null.

Is it working for anyone? Any ideas?

Thanks in advance

**Comment by nick2687** [comment]
Did you ever find a resolution to this?

**Comment by gfosco** [comment]
I assume this works as directed..  If you're having a problem please open a new issue and provide reproduction steps.  I double checked the code paths and this all looks correct.
