### ISSUE TITLE
How can I use PHP to create/delete Parse Schema and change its fields

### ISSUE THREAD

**Issue by itsursujit** [parse-community/parse-php-sdk#343]
Hello,

Thank you for providing such great platform to work on. I was looking a way in PHP to create migration for Parse Schema Structure so that I could sync the changes in structure among different platforms: dev, stage and production.

Any information or guidelines would help.

**Comment by montymxb** [comment]
There's no one solution for handling schema synchronization in the php sdk, but there are some suggestions.

There's always the `ParseSchema` class for directly working on the schema itself. Making it easy to modify fields without having to create/delete an object to force the same. 

There's also the fact that you can [subclass](http://docs.parseplatform.org/php/guide/#subclassing-parseobject) `ParseObject` to create your own managing class for the relevant class in parse. Any relevant setup code for a new class could perhaps be added to there as something like `MyParseClass::setupSchema`, of course this is completely up to you. From there you could add some logic to setup the schema for this class on run, or on some particularl conditions. Other than that you would either have to setup a new class by hand on each environment or add some other logic to handle fields being added/removed/modified. Again, there's no one way to do this.

**Comment by itsursujit** [comment]
Hi Benjamin,

Thank you for your previous response. I've found ParseSchema does everything that I needed.
