### ISSUE TITLE
Ability to encode/decode ParseObject

### ISSUE THREAD

**Issue by tutchmedia** [parse-community/parse-php-sdk#344]
Hi, 

I'm currently attempting to 'snapshot' an object from a class for use as a archive of the row. Is there a way of doing this as every attempt currently fails with a batch save cycle error.

I need to be able to re-use the object later on so i can see a historic look alongside the latest version?

Thanks

**Comment by montymxb** [comment]
Not 100% sure what you're trying to do here...could you describe what you're doing in more detail @tutchmedia ?

**Comment by montymxb** [comment]
Not sure if you're going to follow up with this, so closing it for now. As for saving an 'archived' version of an object you could use a number of approaches, such as creating a copy of an existing object to archive instead for example. Effectively whatever would best suite your needs for archival functionality in the end.

**Comment by tutchmedia** [comment]
@montymxb - Sorry for the late reply, happened to be on vacation after posting for the weekend. 

I'm currently using _encode and good to have confirmation about no 'decode' - do you know when we're likely to see it?

Also, many thanks for the help 👍

**Comment by montymxb** [comment]
Hey no problem! Sorry if I closed this a bit prematurely then. I'm going to reopen this regarding the lack of a **decode** method. 

It's something that I've thought about for some time, it would be nice to have the ability to **encode** and **decode**, allowing one to turn an object into a string and back into an object again could be very useful.

If I'm getting the right idea that this is mostly focused on having an **encode**/**decode** system I'll go ahead and rename this issue to reflect that. Let me know if I'm off and there's something more specific you want to have addressed.

As for when we could have this in, it could be a few weeks at least. It's not terribly difficult, but I'll be out for about 2 weeks this coming weekend. I'll see if I can't get around to it before then.

As for what this entails...I've always had beef with the naming of **_encode**, doesn't feel quite right calling `$obj->_encode()` when it could just be `$obj->encode()`. However to retain reverse compatibility we would have to keep the former method name, but we _could_ add a `ParseObject::encode` method that calls down to `ParseObject::_encode`. What would be left there is to add the class name into the encoding process, without overwriting any existing keys. To wrap it up we would have to `ParseObject::decode` method to get back the object in question.

A quick summation of this would be as follows:
```php
$obj = new ParseObject('MyClass');
// set some key/value pairs & save
$obj->save();

// would encode this object
$encoded = $obj->encode();

// would decode this object
$decoded = ParseObject::decode($encoded);
```

**Comment by tutchmedia** [comment]
@montymxb - No problems at all with closing prematurely, it serves me right for asking a question before a vacation! Thanks for re-opening though :)

This sounds like exactly what I need for my project. Looking forward to seeing the progress although don't stress too much with going away :)

Thanks

**Comment by tutchmedia** [comment]
Hi @montymxb - Hope you had a nice break and welcome back! I was just wondering if this is still something you'd be able to look into?

Appreciate the help :)

**Comment by montymxb** [comment]
@tutchmedia break was good! I was looking into this a couple days ago actually, haven't finished it up yet but I do have something in the works.

**Comment by montymxb** [comment]
#351 adds in support for object encoding/decoding exactly as mentioned above ^. I'll be moving forward with a **1.3.0** release as there's a few new features (hhvm support for example) that are not present in the current **1.2.10** release.

I'll be following up with some bits of documentation for this as well before i move forward with **1.3.0**. Depending on how you're referencing this project you can get the changes immediately if  you track the master branch, or if you're using composer you can get them once the new version is released.
