### ISSUE TITLE
ParsePush iOS ?

### ISSUE THREAD

**Issue by hopye** [parse-community/parse-php-sdk#345]
Hi there guys,

Is there a way to send Title and Body  ? i see the parse push only sends the body of the message without title..

**Comment by hopye** [comment]
This depends on Parse Server to be able do that right ?

**Comment by montymxb** [comment]
@hopye the **title** and **alert** properties are supported under the **data** property in a payload for push requests, as specified in the [parse-server guide](http://docs.parseplatform.org/parse-server/guide/#api).

An example of doing that would be as follows.
```php
ParsePush::send(
	[
		'channels' => [''],
		'data'     => [
			'alert' => 'Your Push Message',
			'title'	=> 'Your Push Title'
		],
	],
	true
);
```

**Comment by montymxb** [comment]
Closing this out as this hasn't been followed up for about 3 weeks
