### ISSUE TITLE
Failed to connect to <IP> port <Port>: Connection timed out

### ISSUE THREAD

**Issue by shardul08** [parse-community/parse-php-sdk#353]
whenever the command:
**_git push origin master_**
is given, the following error is shown:
**_Failed to connect to 172.16.0.16 port 8080: Connection timed out_**

I have tried connecting to several networks but I am encountering the same error all the time.
I am new to git and Linux and can't understand these errors properly.
Please help

![whatsapp image 2017-09-14 at 2 04 14 am](https://user-images.githubusercontent.com/26631311/30399619-e2a9acb2-98f1-11e7-9dad-b48841b0fd07.jpeg)

**Comment by montymxb** [comment]
This is completely unrelated to the php sdk...

You probably need to read [the git book](https://git-scm.com/book/en/v2) or their documentation to figure out issues related to git.
