### ISSUE TITLE
Parse Query EqualTo() into SubObject with dot notation

### ISSUE THREAD

**Issue by tutchmedia** [parse-community/parse-php-sdk#356]
Hi,

ParseQuery includeKey() supports dot notation to include keys within a subObject, ie. given the following structure

- Home Parse Class
  - Owner Object
      - Name

You're able to 

`$query->includeKey("owner.name");`

To include the owner names in the result. I'm presuming this would work at least, maybe not for object types?

It doesn't seem like you can use the same dot notation with equalTo() ie. 

`$query->equalTo("owner.name", "Joe Bloggs");`

even though the underlining mongo query

`db.getCollection('Homes').find({"Owner.Name" : "Joe Bloggs"})`

Does exactly what you want.

Is this something that is possible with parse, or support of which could be added? Or alternatively is there any scope for somehow being able to perform a mongo query and have parse pass it through to mongo directly and return the appropriate objects?

Thanks in advance!

**Comment by tutchmedia** [comment]
Actually, upon further investigation it seems that this is now supported?

The actual example that I'm using was trying to query against a subobject's property that was an Int but had been incorrectly loaded into the subobject as a String containing that int. When I then queried equalTo() an Int it would never match against the data's String version. Fixing up so that the subobject's property's data type matches the equalTo() query's type and now the query seems to be working ok.

Is this what we would expect, that dot notation is functional in some capacity for subobjects in equalTo() ?

Cheers

**Comment by montymxb** [comment]
@tutchmedia sorry about the delayed response. I was wondering if this was actually possible myself, so I went ahead and ran the following locally:
```php
$obj1 = new ParseObject("TestObject");
$obj1->set('name', 'obj1');
$obj1->save();

$obj2 = new ParseObject("TestObject");
$obj2->set('name', 'obj2');
$obj2->set('child', $obj1);
$obj2->save();

$query = new ParseQuery('TestObject');
$query->includeKey('child');
$query->equalTo('child.name', 'obj1');
$found = $query->first();

// expecting $found to be $obj2
```
No dice for me however, so this does not seem to be the case. If you have a working example locally I would love to see it though! It is believable that something like this _could_ work, assuming the key is not mangled due to the separating `.`.

**Comment by dplewis** [comment]
@montymxb I believe the include pointers are handled after `find()`. Dot notation currently works on objects not pointers. A solution to this would be to use aggregates.

**Comment by montymxb** [comment]
Aggregates would be a solid approach to the issue outlined above 👍 .

On another note @dplewis nested includes do work on pointers, as can be seen in [this test](https://github.com/parse-community/parse-php-sdk/blob/master/tests/Parse/ParseQueryTest.php#L1875). Pretty sure it's all handled server-side as well. I don't believe they go more than 1 deep past the root however.

**Comment by flovilmart** [comment]
> Dot notation currently works on objects not pointers

Dot notation works on pointers and is actually well tested. Going the aggregate route for that is just a guaranteed path to hell!

> I don't believe they go more than 1 deep past the root however.

They are fully recursive server side.

**Comment by dplewis** [comment]
> Dot notation works on pointers and is actually well tested. Going the aggregate route for that is just a guaranteed path to hell!

Is that true for using dot notation in equalTo on a pointer?

**Comment by flovilmart** [comment]
It should, otherwise that’s a bug, but it’s well covered and tested

**Comment by dplewis** [comment]
Its there a test somewhere similar to @montymxb earlier test https://github.com/parse-community/parse-php-sdk/issues/356#issuecomment-339162787 ?

**Comment by flovilmart** [comment]
I dunno, the best way to find out is to write a failing test and open a PR with it.

**Comment by montymxb** [comment]
@dplewis There's no test in this sdk similar to the code I posted above (maybe there's something server-side?). I put that up just mentioning that I took a look at it myself. Unfortunately it doesn't quite work as expected.

I did take a look at server-side and remembered there was _something_ about the `.` being mangled or otherwise omitted when passed for **equalTo**...it's hard to say, sorry I can't be more exact. 

From what I do remember the server should be capable of supporting dot notation, but there was just one part that was altering the query key preventing it on equalTo specifically (this may no longer be the case if it has since changed).

**Comment by dplewis** [comment]
I tried looking into it on the server side. I’ll try again later maybe I missed something.

**Comment by acinader** [comment]
I haven't looked into the solution yet, but here's the failing test.

**Comment by dplewis** [comment]
Is this issue about Dot Notation on pointers or sub objects? Based on the second comment it seems nested objects.

**Comment by acinader** [comment]
I don't understand the difference offhand.  I took what @montymxb did in https://github.com/parse-community/parse-php-sdk/issues/356#issuecomment-339162787 and just out it into a unit test (though I changed the words to make it easier for me to understand what I was doing.)

**Comment by dplewis** [comment]
ParseObject vs Associative Array in this SDK.

Dot Notation works on nested objects because the data is already there when querying.

I don’t think work on pointer values because we query first then included pointers so we can never query on the pointers values.

**Comment by dplewis** [comment]
Closing as equalTo on dot notation (type object) is already implemented.

equalTo on a pointer would require a server side update and would add complexity.
