### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in src/Parse/ParseObject.php

### ISSUE THREAD

**Issue by fvimagination** [parse-community/parse-php-sdk#375]
### Issue Description

Hi there, I'm getting this issue while loading my websites with Parse PHP SDK today, it's been an hour so far.
I also get this error about ParseQuery.php: Warning: Invalid argument supplied for foreach() in src/Parse/ParseQuery.php

### Steps to reproduce

Just try this website: [http://fvimagination.com/events/index.php](url), it seems there's an issue on ParseObject.php

### Environment Details

- Your PHP Version: **[7]**
- Your Parse PHP SDK Version: **[1.3.0]**
- Your Operating System: **[macOS Chrome browser]**

**Comment by soniurvashi11** [comment]
Try printing your error, it will give you exact line number in which foreach is throwing error. And then you can find out what argument you are passing which is invalid, several reasons can be associated with invalid argument, eg. not an array, empty, null etc.

**Comment by fvimagination** [comment]
1. I don't know how to print an error of the Parse SDK
2. Sometimes it goes smoothly and runs the page, other times it throws that Warning, so I guess there's something wrong in the SDK, not in my code because it was working perfectly until 2 hours ago...

**Comment by fvimagination** [comment]
Btw, here's the lines numbers:
```
Warning: Invalid argument supplied for foreach() in /home/fvima186/public_html/events/src/Parse/ParseObject.php on line 634

Warning: Invalid argument supplied for foreach() in /home/fvima186/public_html/events/src/Parse/ParseObject.php on line 670

Warning: Invalid argument supplied for foreach() in /home/fvima186/public_html/events/src/Parse/ParseObject.php on line 634

Warning: Invalid argument supplied for foreach() in /home/fvima186/public_html/events/src/Parse/ParseObject.php on line 670
```

**Comment by soniurvashi11** [comment]
So are u calling "_mergeAfterFetch" of parse SDK, from ur php file?

**Comment by soniurvashi11** [comment]
Try putting try catch on the function .. in ur php file ( and not SDK file ) and in catch u can print_r error

**Comment by fvimagination** [comment]
I already did that for my query in my index.php file, but it doesn't print any error, just those warnings relative to ParseObject, so not my code but the Parse PHP SDK code...

**Comment by fvimagination** [comment]
> So are u calling "_mergeAfterFetch" of parse SDK, from ur php file?
No, I never used that command in my code.

**Comment by soniurvashi11** [comment]
You will have to find out which method you are calling, which is giving u error!

**Comment by fvimagination** [comment]
This is what I call in the first block, as soon as the page gets loaded:
```
   // Get parse Object by its objectID
    $eObjID = $_GET['eObjID'];
   
     try {
      $eObj = new ParseObject("Events", $eObjID);
      $eObj->fetch();

      // Get title
      $title = $eObj->get('title');
      echo $title;
    
    // error 
    } catch (ParseException $e){ echo $e->getMessage(); }
  
```
This code was working fine until 2 hours ago, it's all I know, because it doesn't print any error in the catch function.

**Comment by soniurvashi11** [comment]
```
// Get parse Object by its objectID
    $eObjID = $_GET['eObjID'];
   
     try {
      $query = new ParseQuery("Events");
      $query->equalTo("objectId",$eObjID);
      $eObj = $query->first();

      // Get title
      $title = $eObj->get('title');
      echo $title;
    
    // error 
    } catch (ParseException $e){ echo $e->getMessage(); }
```

> Can u try using this? Make sure $_GET['eObjID'] has an objectId, if this works for u, I will tell u the bugs.

**Comment by fvimagination** [comment]
I did, and it actually works, so do you mean that the `fetch()` function doesn't work anymore on Parse PHP SDK?
```
 $eObj = new ParseObject("Events", $eObjID);
 $eObj->fetch();
```

**Comment by fvimagination** [comment]
UPDATE: It stopped working again:

```
Warning: Invalid argument supplied for foreach() in /home/fvima186/public_html/events/src/Parse/ParseQuery.php on line 603

Fatal error: Call to a member function get() on array in /home/fvima186/public_html/events/event-details.php on line 46
```

Here's my code:

`// Get parse Object by its objectID
    $eObjID = $_GET['eObjID'];
   
     try {
      $query = new ParseQuery("Events");
      $query->equalTo("objectId", $eObjID);
      $eObj = $query->first();

      // Get title
      $title = $eObj->get('title');
  
      // Get description
      $description = $eObj->get('description');
  
      echo '
        <title>' .$title. '</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="' .$description. '">
    ';
     
    // error 
    } catch (ParseException $e){ echo $e->getMessage(); }
`

**Comment by soniurvashi11** [comment]
No not really, fetch works..
But I think with the ParseQuery or if u want to use ParseObject, u have to set some value and so.. m not sure, have not worked with fetch before, have limited information about it. Please search and lemme know, :)

**Comment by soniurvashi11** [comment]
Looks like ur $eObj is empty, try printing it using print_r($eObj), if empty that means either u r providing wrong objectId or name of model 'Events' is wrong!

**Comment by fvimagination** [comment]
I could successfully use fetch(); since 2 hours ago, it's been 2 months I'm using it :)
Anyway, my site stopped working even with the ParseQuery you posted above, I'm also launching a query in index.php, and it throws the same warning, so now even the ParseQuery is not working fine...

**Comment by fvimagination** [comment]
My $eObj is not empty, it's a $_GET variable:

```
$eObjID = $_GET['eObjID'];
print_r($eObjID);
// prints: iUqVPNtvoo
```

**Comment by soniurvashi11** [comment]
Talking about  $eObj and not $eObjID.. :)

**Comment by fvimagination** [comment]
yep, it successfully gets printed out (the $eObj pare object) :)

`Parse\ParseObject Object ( [serverData:protected] => Array ( [title] => LAST: Wedding Event in NYC [description] => lorem ipse dolor quantum lorem ipse dolor quantum lorem ipse dolor quantum lorem ipse dolor quan etc...`

**Comment by fvimagination** [comment]
so, it seems the issue come out when i add this line:

`$title = $eObj->get('title');`

if i comment it out, and i print `$eObj`, it works smoothly even with the `fetch()` function...

**Comment by fvimagination** [comment]
I confirm this is an issue with the 1.3.0 version of this SDK because I've just uploaded an older version of the **src/Parse** folder on my server and my website is working perfectly.

**Comment by soniurvashi11** [comment]
I see, I m still using, 1.2.0

**Comment by fvimagination** [comment]
actually, i’ve discovered that it may be a back4app server issue, because i’ve hosted Parse Server on Heroku and it works smoothly, so i’m gonna close this issue since it  seems that Parse php sdk is fine.
thanks for your help anyway!

**Comment by montymxb** [comment]
Glad to see you've managed to resolve it @fvimagination . For future reference `first` will return an empty array if no object is found, rather than the expected object (or null). Be sure to sanity check what you're getting back from a query before you assume it's a valid object, especially from `first`. It's likely that the **eObjID** you were expecting to match was not actually valid in one case or another.

**Comment by fvimagination** [comment]
It simply was a back4app strange server issue, I've contacted those guys and they fixed it :)
