### ISSUE TITLE
Persistent Storage and Parse PHP SDK?

### ISSUE THREAD

**Issue by acinader** [parse-community/parse-php-sdk#380]
@montymxb :).

So if I use parse php on multiple servers, I need to "roll my own" persistent session storage?  

I'm @ aws on elastic beanstalk, so contemplating using dynamo db for session storage, but this feels ridiculous cause I already have a configured setup to by parse backing store.  Wouldn't it make sense for the parse php sdk to expose a ParseStorageInterface that uses the parse backing store to persist sessions??

am i missing something?

**Comment by acinader** [comment]
Ok, i see.  It's not a matter of just the ParseStorage, but all cookie storage....

**Comment by montymxb** [comment]
Yep 👍 . There are two primary mechanisms for local storage in this SDK. The primary being session storage and the alternate being memory storage, the later not really being that helpful quite frankly as you can't persist logins across loads. The sdk will favor the former, providing a session has been started before this is initialized.

**Comment by montymxb** [comment]
Not quite cookie storage by the way. Although a cookie will be stored client side that contains the session id, that's about it. The actual data being stored in the session is maintained server side and is available to the user providing the correct cookie value.
