### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in ParseObject class

### ISSUE THREAD

**Issue by Ankit-Khachane** [parse-community/parse-php-sdk#384]
### Issue Description
Php Parse api is not working properly,
I am getting this error on saving data on my parse server app over **back4app** for following data
```
$object = ParseObject::create("TableTest");

$object->set("Animal", "elephent");
$object->set("today", new DateTime());
$object->setArray("mylist", [1, 2, 3]);

$object->save(); 
```
### Environment Details

- Your PHP Version: **7.0.23**
- Your Parse PHP SDK Version: **1.4.0**
- Your Operating System: **windows 10**

### Logs/Traces
 Warning: Invalid argument supplied for foreach() in 
**C:\ ...\vendor\parse\phpsdk\src\Parse\ParseObject.php on line 631**

**Comment by montymxb** [comment]
@Ankit-Khachane This looks like a response from the server may not be as expected, assuming the error is on [line 631](https://github.com/parse-community/parse-php-sdk/blob/master/src/Parse/ParseObject.php#L631) as mentioned. 

If you could provide the full exception stack trace that would be much more helpful to determine the exact path of execution that is causing this. Feel free to redact any sensitive data as needed.

We have test cases that account for this functionality, but they predominantly run on a linux box. Considering that it's possible that this may be windows related, not necessarily the case but an option to consider while investigating.

**Comment by montymxb** [comment]
Closing this out as you haven't followed up. If this is still an issue let us know so we can reopen and address it, and with details!
