### ISSUE TITLE
Facebook login doesn't save authdata

### ISSUE THREAD

**Issue by nuborian** [parse-community/parse-php-sdk#390]
Hey :) 
Anyone is using the php SDK? I am trying to login via Facebook (which is working) but it doesn’t save the data to the authdata Object in the User table.
Any experience? Or is there an additional Step necessary?

Best Nico

**Comment by montymxb** [comment]
@nuborian When you login a user with a 3rd party auth you should also link them with a 3rd party auth. For facebook that would be calling something like `$user->linkWithFacebook`. From there it should associate 👍 .
