### ISSUE TITLE
Outstanding CI Issue

### ISSUE THREAD

**Issue by montymxb** [parse-community/parse-php-sdk#398]
### Issue Description

CI Fails to run due to an issue related to staring up a test parse server to run against.

### Steps to reproduce

Any PR will fail CI due to the ongoing issue. Refer to [this job](https://travis-ci.org/parse-community/parse-php-sdk/jobs/371182091) for an example.

### Environment Details

- Your PHP Version: all
- Your Parse PHP SDK Version: latest
- Your Operating System: linux (talking about travis specifically, but this will happen on others as well)
- VM (only if you're running something like HHVM): any

### Logs/Traces

Refer to job link above for details.

This is more to make it known that we're aware of this and will be resolving it. Beyond that the SDK itself should be just fine.

**Comment by dplewis** [comment]
@montymxb This has been addressed in Parse Server 2.8.1.

https://github.com/parse-community/parse-server/pull/4771/files

**Comment by montymxb** [comment]
Thanks for letting me know @dplewis . I took a look locally and was able to spin things up for testing. There are some errors related to what look like feature changes in the server, will have to iron them out once I can get the CI cache cleared out to reflect the changes server side.

**Comment by dplewis** [comment]
@montymxb Cool, there are lot of features that need to be added.

**Comment by acinader** [comment]
this appears to be fixed.
