### ISSUE TITLE
parse-php-sdk

### ISSUE THREAD

**Issue by Immowebian** [parse-community/parse-php-sdk#400]
Hi can anyone solve this issue. i've trying from last 2 days. but it still there.

I done this but not worked at all.

$query = new ParseQuery("Event");
$query->equalTo("event_name", "event1");
$question = $query->find();
for($i=0;$i;$i++){
$question[$i]->set("event_city", $event_city);
$question[$i]->set("event_state", $event_state)
$question[$i]->save();
}
@soniurvashi11

**Comment by Immowebian** [comment]
Any one know the parse and php ?

**Comment by dplewis** [comment]
@Immowebian Sorry for the late reply. It look like your for loop expression is wrong. 

Should be `for ($i = 0; $i < count(question); $i++)`
