### ISSUE TITLE
How to use cachePolicy and cacheMaxAge in parse php?

### ISSUE THREAD

**Issue by hamzabinamin** [parse-community/parse-php-sdk#409]
### Issue Description
I have been using Parse SDK in my android and iOS application. In the mobile SDK's there was an option to include cache policy while doing a query which helped us to store some of the results in a cache to speed up searching. However now that we're building a website using the PHP SDK, I can't seem to find a similar function that lets us do that.

**Comment by acinader** [comment]
There is no query cache built in.  If you need caching, you'll need to provide it in a way that is appropriate for your app and how it is deployed.  Sorry.
