### ISSUE TITLE
class 'ParseClient' not found in index.php

### ISSUE THREAD

**Issue by JGK01** [parse-community/parse-php-sdk#410]
### Issue Description

i just tried to install parse php sdk, i installed it with the git clone command, but when i try to do ParseClient::initialize(...) i got the error : 

 Fatal error: Class 'ParseClient' not found in /path/to/index.php on line 8

i checked that the access to autoload.php was ok and it seems to be good. 

i don't know what to do with that issue, any idea ? 

- Your PHP Version: 5.5.9
- Your Parse PHP SDK Version: 1.4.0
- Your Operating System: Ubuntu

**Comment by acinader** [comment]
Can you install using composer?  Your php script doesn't know how to find the parse library.  Please review the installation instructions in the project readme.
