### ISSUE TITLE
Can not run set operation and save

### ISSUE THREAD

**Issue by MrMegamind** [parse-community/parse-php-sdk#415]
I am running following code

		$hubr_messenger_message = ParseObject::create("hubr_messenger_message");
		$hubr_messenger_message->set("msg_id", $parse_arr->msg_id);
		$hubr_messenger_message->save();

and get following error
Fatal error: Interface 'Parse\Internal\FieldOperation' not found in /includes/sdk/parse/php-sdk/src/Parse/Internal/SetOperation.php on line 17

This is file structure of sdk/parse/php-sdk/src/Parse/Internal    http://prntscr.com/l0mcaa

I assume we are missing a file here?

Documentation here states there should be a file FieldOperation.php in internal
http://parseplatform.org/parse-php-sdk/namespaces/Parse.Internal.html

**Comment by MrMegamind** [comment]
I downloaded raw file and uploaded but still no luck, same error:

Fatal error: Interface 'Parse\Internal\FieldOperation' not found in /includes/sdk/parse/php-sdk/src/Parse/Internal/SetOperation.php on line 17

**Comment by acinader** [comment]
Have you gone through the installation and getting started sections of the guide?

https://docs.parseplatform.org/php/guide/#installation
