### ISSUE TITLE
Include Issue

### ISSUE THREAD

**Issue by kevinmthornton** [parse-community/parse-php-sdk#43]
Hi Forum,

I have coded in PHP in the past but, not for a few years now. I have included the 'autoload.php' file and confirmed that it is including the Parse/ParseClient.php file by just putting in a line to display on the screen in ParseClient.php.

My error is: 

Fatal error: Class 'ParseClient' not found in /Users/kevint/Documents/local-web-host/index.php on line 11

Here is my code sans my real ID's:

<?php
ini_set('display_errors', true);

require "autoload.php";

// you get these from parse.com/settings > Keys
$app_id = "blah";
$rest_key = "blah";
$master_key = "blah";

ParseClient::initialize( $app_id, $rest_key, $master_key );

echo "parse initialization<p>";

$query = new ParseQuery("Birthday");
try {
  $timsBirthday = $query->get("BLAH");
  // The object was retrieved successfully
  echo "tim's birthday " . $timsBirthday;

} catch (ParseException $error) {
  // The object was not retrieved successfully.
  // error is a ParseException with an error code and message.
  echo $error->getCode();
  echo $error->getMessage();
}
?>

I am running PHP 5.4.30 on a Mac Mini using http://localhost:8888 as my local web server. This is pretty basic and I have followed the instructions, _I think_. Any help would be appreciated.

K

**Comment by aneesu401** [comment]
can you share the working code after you made the change. because  i'm stuck with the same problem.

**Comment by hjgabrielsen** [comment]
Anychance of sharing the working code?  i'm stuck with the same problem.

**Comment by montymxb** [comment]
@hjgabrielsen something like this should do the trick.
```php
require "parse-php-sdk/autoload.php";

use Parse\ParseClient;

ParseClient::initialize("appId", "restKey", "masterKey");
ParseClient::setServerURL('http://localhost:1337', 'parse');

// other code below...
```
This is assuming you cloned the repo directly from github, otherwise use `require "vendor/autoload.php";` for composer.

If you're still having problems with not finding the class it's possible the path being used to require the autoloader is not correct. I would double check that to make sure you've got the actual path to `autoload.php`.

You can also check out the [php guide](http://docs.parseplatform.org/php/guide/) for more details.

**Comment by hjgabrielsen** [comment]
Thanks :-)
Hmm, 
If i do 
```
require "/folders/autoload.php";
use Parse\ParseClient;
ParseClient::initialize("appId", "restKey", "masterKey");
ParseClient::setServerURL('https://api.parse.com/parse:1337', 'program');
```
I get : Fatal error: Uncaught exception 'Exception' with message 'You must call Parse::initialize() before making any requests.' 

if i do:
```
ParseClient::initialize("appId", "restKey", "masterKey");
ParseClient::setServerURL('https://api.parse.com/parse:1337', 'program');
require "/folders/autoload.php";
use Parse\ParseClient;
```
i get Fatal error: Class 'ParseClient' not found in /home/admin/web/public_html/filename.php on line 30
