### ISSUE TITLE
How to use $ geoNear with aggregate؟

### ISSUE THREAD

**Issue by eslam2010011** [parse-community/parse-php-sdk#434]
### Issue Description

my code 
![image](https://user-images.githubusercontent.com/21963428/53244087-77976580-36b2-11e9-8e66-49b0d7b9756a.png)

### Steps to reproduce

~~ Please provide the necessary steps here to reproduce this when possible ~~

### Environment Details

- Your PHP Version: **[1.5.1]**
- Your Parse PHP SDK Version: **[3.1.3]**
- Your Operating System: **[your OS here]**
- VM (only if you're running something like HHVM): **PHP**

### Logs/Traces

~~ Include any relevant logs/traces here ~~

**Comment by dplewis** [comment]
Closing as this isn't an issue. From the mongo docs, `near` takes a GeoJSON point or legacy coordinate pair. Not a ParseGeoPoint as geopoints aren't currently converted to those types.
