### ISSUE TITLE
Unable to login users Parse PHP 1.5.1

### ISSUE THREAD

**Issue by Ant248** [parse-community/parse-php-sdk#435]
Unable to login in version 1.5.1 error:
Parse\ParseException: Bad Request in 
api/src/Parse/ParseClient.php:579

1.4 works fine here is the code im using to try login my users:

try {
    $user = Parse\ParseUser::logIn($ema, $pas);
    // Do stuff after successful login.
}

Has there been a breaking change betwen the versions? Unable to find any differences in the documentation.

**Comment by dplewis** [comment]
Please update your Parse Server.

https://github.com/parse-community/parse-php-sdk/pull/430

**Comment by Ant248** [comment]
Thanks I using sashido cloud based parse server its showing v2.3.3 i see this is not acttually the latest.. 
thanks for clarification!
