### ISSUE TITLE
Can't delete or destroy

### ISSUE THREAD

**Issue by kevinmthornton** [parse-community/parse-php-sdk#44]
Hi Forum,

Me again. Working with the API documentation and things were going well until I tried to delete a field or destroy an object. I can create, retrieve and update fine. However, when I try to destroy() the object, I get the following error:

Fatal error: Uncaught exception 'Parse\ParseException' with message 'object not found for delete' in /Users/kevint/Documents/local-web-host/src/Parse/ParseClient.php:258 Stack trace: #0 /Users/kevint/Documents/local-web-host/src/Parse/ParseObject.php(643): Parse\ParseClient::_request('DELETE', '/1/classes/Birt...', NULL, NULL, false) #1 /Users/kevint/Documents/local-web-host/index.php(30): Parse\ParseObject->destroy() #2 {main} thrown in /Users/kevint/Documents/local-web-host/src/Parse/ParseClient.php on line 258

Here is my code. I can see it echo out the value of $timsBirthday fine but, get the error right after this.

$query = new ParseQuery("Birthday");
// just get a specific record
try {
  $timsBirthday = $query->get('mmSHXt6GpO');
   //The object was retrieved successfully
  echo "<p>tim's birthday " . $timsBirthday->get("name") . "</p>";
  // $timsBirthday->delete('name');
  // $timsBirthday->save();
  $timsBirthday->destroy();
} catch (ParseException $error) {
   //The object was not retrieved successfully.
   //error is a ParseException with an error code and message.
  echo $error->getCode();
  echo $error->getMessage();
}

For the delete()/save() methods, I get this error:

Fatal error: Uncaught exception 'Parse\ParseException' with message 'object not found for update' in /Users/kevint/Documents/local-web-host/src/Parse/ParseClient.php:258 Stack trace: #0 /Users/kevint/Documents/local-web-host/src/Parse/ParseObject.php(919): Parse\ParseClient::_request('PUT', '/1/classes/Birt...', NULL, '{"name":{"__op"...', false) #1 /Users/kevint/Documents/local-web-host/src/Parse/ParseObject.php(830): Parse\ParseObject::deepSave(Object(Parse\ParseObject), false) #2 /Users/kevint/Documents/local-web-host/index.php(29): Parse\ParseObject->save() #3 {main} thrown in /Users/kevint/Documents/local-web-host/src/Parse/ParseClient.php on line 258

**Comment by nitrag** [comment]
What was your solution. I am getting the same exception when using Destroy() however the object does get deleted...

**Comment by christopherdev** [comment]
try ->destroy(true);

**Comment by nitrag** [comment]
Thanks for the help Christopher, unfortunately I was already doing this and it didn't help. The exception is nearly identical to @kevinmthornton. 

```
$query = new ParseQuery("Photos");
$query->includeKey("uploadedBy");

try{
	$pic = $query->get($parseId);
	if($method == "approve"){
		$pic->set("approved", true);
		$pic->save();
		echo "Approved!";
	}else if($method == "dispose"){
		$created = $pic->get("uploadedBy");
		if($created){
			$created->increment("abuses");
			$created->save();
		}
		
		//find associated posts and also remove
		$query2 = new ParseQuery("Activity");
		$query2->equalTo("Image", $pic);
		$query2->includeKey("Image");
		$results = $query->find();
		foreach($results as $post){
			$post->destroy(true);
		}
		$pic->destroy(true);  //this line is the exception
		echo "Desroyed!";
	}
} catch (ParseException $ex) {
	// error in $ex->getMessage();
	echo "Error - ".$ex->getMessage();
}
```

apache error because I get 500 error when running script (method == "approve" works fine and does not have 500 error so it's not syntax)
```
PHP Fatal error:  Uncaught exception 'Parse\\ParseException' with message 'object not found for delete' in /var/www/html/otg-website/parse-sdk/src/Parse/ParseClient.php:346\nStack trace:\n#0 /var/www/html/otg-website/parse-sdk/src/Parse/ParseObject.php(749): Parse\\ParseClient::_request('DELETE', 'classes/Photos/...', 'GdGYZbwMKhqQBCD...', NULL, false)\n#1 /var/www/html/otg-website/ajax/approveImages.php(37): Parse\\ParseObject->destroy()\n#2 {main}\n  thrown in /var/www/html/otg-website/parse-sdk/src/Parse/ParseClient.php on line 346, referer: http://maps.overlandr.mobi/otg-website/admin-images.php

```

**Comment by nitrag** [comment]
Please close this, it was a typo in my code. It had to do something with not setting up all the namespace's I needed.
