### ISSUE TITLE
Parse Query for value 0 (Zero) not working 

### ISSUE THREAD

**Issue by mobappsbr** [parse-community/parse-php-sdk#454]
I`m trying do a query in a Class where I have a field of type ‘Number’ in Parse Server, my query:

```
    $query = new ParseQuery($className);
    $query->equalTo("number",0);
    $query->count();
```
When I query for other numbers like 30, 50, 1, get the total right, but for zero get all Objects(total) in this class. I tried do this query in Parse Dashboard and results seems ok, the problem is only in Parse SDK PHP.

**Comment by dplewis** [comment]
@mobappsbr I wrote a test case and it passed. Can you look at it?

https://github.com/parse-community/parse-php-sdk/pull/455
