### ISSUE TITLE
Aggregate pipeline > Multiple lookup stages

### ISSUE THREAD

**Issue by michaelpeterlee** [parse-community/parse-php-sdk#462]
### Issue Description

Q. Does the SDK support lookup/left-join 2x related classes?

The SDK implementation refers PHP implicit object notation;  
We cannot redeclare 'lookup'.

I tried to pass a 2D object, to no-avail.

### Steps to reproduce

```
$pipeline =
   [
         'lookup' =>
            [
                  [
                     'from' =>"_User",
                     'localField'=> "userObjectId",
                     'foreignField' => "_id",
                     'as' => "user"
                  ],
                  [
                     'from' =>"Article",
                     'localField'=> "articleObjectId",
                     'foreignField' => "_id",
                     'as' => "article"
                  ],
           ],
   ];
```

### Environment Details

Your PHP Version: [ 7.2.24]
Your Parse PHP SDK Version: [1.6]
ParseServer: V3.2.3, NodeJS 10.15.1, MongoDb 3.4

**Comment by smamun56** [comment]
any whay to solve this issue ?

**Comment by dplewis** [comment]
This issue has been fixed in Parse Server 6. Please create a new issue if this persists.
