### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by isaacaskew** [parse-community/parse-php-sdk#485]
I'd like to add some new code to the PHP client so that we can take advantage of some of the features in later versions of Parse Server - notably `/loginAs` (https://github.com/parse-community/parse-server/blob/alpha/src/Routers/UsersRouter.js), so I'd make change to `ParseUser.php` in this repo.

I read the contributing guidelines and one of the forms required to start contributing is missing. Separately, I'd like to know where to target the PR (and others) since this will specifically be a function that calls a route that only exists in some of the more recent versions  of Parse Server, and doesn't make sense as a patch to this minor version.

How can I start to contribute?

**Comment by mtrezza** [comment]
Thanks for you interest in contributing.

You could just open an issue to describe the bug fix / feature request and maybe after some feedback add the PR for it.

**Comment by isaacaskew** [comment]
@mtrezza - the guide [here](https://github.com/parse-community/parse-php-sdk/blob/b6ad14abea7ddd54eaba60ccd0dbeb4f3a240d23/CONTRIBUTING.md) suggests we must sign a Contributor License Agreement - I found it by opening a new issue - once you're filling out the new issue subject & body, it's a link in the bottom right under 'Helpful resources'.

And sounds good re: contributing, I'll open a PR soon.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.1.0](https://github.com/parse-community/parse-php-sdk/releases/tag/2.1.0)
