### ISSUE TITLE
Add auto-release

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-php-sdk#493]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-php-sdk/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-php-sdk/issues?q=is%3Aissue).

### Current Limitation

This repo has no release automation. Publishing a release takes more effort than it should.

### Feature / Enhancement Description

Since packagist registry scans the repo [automatically](https://github.com/parse-community/parse-php-sdk/issues/492#issuecomment-1524098184) and published new releases there, release automation here only needs to incorporate the following tasks:
- Create changelog entry
- Bump SDK version in `ParseClient.php` (maybe via a simple `sed` instruction)
- Create version tag

**Comment by mtrezza** [comment]
Keeping this open until we can see with a PR merge that it actually works

**Comment by mtrezza** [comment]
It seems that the sed command has a slightly different syntax on ubuntu.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.1.0](https://github.com/parse-community/parse-php-sdk/releases/tag/2.1.0)
