### ISSUE TITLE
Add codecov to CI

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-php-sdk#499]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-php-sdk/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-php-sdk/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse PHP SDK](https://github.com/parse-community/parse-php-sdk/releases). 

### Issue Description

Codecov is missing in the CI jobs list, even though it is being performed in the CI workflow.

**Comment by dplewis** [comment]
What exactly is the issue here?

**Comment by mtrezza** [comment]
There used to be codecov entries in the CI list, but for some reason I can't seem to find them anywhere anymore, not even in the other repos.
