### ISSUE TITLE
Problem with $_SESSION and authentification

### ISSUE THREAD

**Issue by Wanted33** [parse-community/parse-php-sdk#7]
Hi,

I'm trying to use the PHP SDK to make a basic php app but i have a problem with the authentification. Indeed, once a user is log in via the logIn() function I redirect to another page where I try to retrieve the current user by the ParseUser::getCurrentUser() method. However I get an error that appears and I can not solve : 

Fatal error: Cannot use object of type __PHP_Incomplete_Class as array in /Users/quentin/Dropbox/Projets/sites/filmoapp/vendor/parse/php-sdk/src/Parse/ParseUser.php on line 217

I tried to remove the session_start () but if I take it off I do not have any user who is registered in the local session (which is normal). 

Any ideas to solve this problem?

Thanks :-)

**Comment by jqEmprendedorVE** [comment]
Good good good,

Dustyjewett support, this should be in the readme

**Comment by ravi-innctech** [comment]
Thnanks

**Comment by piu-coder** [comment]
Hi all,

I am facing the same issue but in yii framework. here is the error:

Fatal error: Cannot use object of type __PHP_Incomplete_Class as array in /var/www/project-web/protected/vendor/parse-php/src/Parse/ParseUser.php on line 340

 I have tried all the above suggestion but no success. Any help would be appreciated.

**Comment by gfosco** [comment]
If the Yii framework is starting the session before you, you need to look for a way to load the autoloader before that happens.   #136 for example.

**Comment by piu-coder** [comment]
@gfosco: This was helpful and I am finally able to fix the issue. Thanks a lot!
